name: Deploy Vite App to Kubernetes

on:
  workflow_dispatch:

env:
  IMAGE_NAME: vite-app
  IMAGE_TAG: latest
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: http://my-app-url.com
          environment: production

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Write Kubeconfig to file
        run: echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f kube/

      - uses: chrnorm/deployment-status@v2
        name: Update deployment status
        if: success()
        with:
          token: "${{ github.token }}"
          environment: production
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
